### ISSUE TITLE
How can I start contributing?

### ISSUE THREAD

**Issue by stellis** [bdraco/nexia#47]
Hi @bdraco, really appreciate your work here and would like to help. I'm an experienced dev, but I was hoping you could save me some time by giving me an overview of how you maintain this plugin.

Are you just using a local proxy to MITM the Nexia/Trane/AS app's API calls?

I'll try to find out how to work on Home Assistant elsewhere, but any Nexia-specific info is helpful.

**Comment by bdraco** [comment]
I'm using Charles proxy on my iPhone to capture api calls

As far as contributing, feel free to open a PR
