### ISSUE TITLE
Nexia integration no longer working.

### ISSUE THREAD

**Issue by myshiftzz** [bdraco/nexia#7]
I saw your comment on the other thread about the change only affecting AS devices.  I have an AS device (XL824?).  Is this an issue that I need to wait for a fix?  

Copying issue from other thread to here.
---------------
Nexia changed websites. I am assuming this is why my nexia integration no longer works.

The new website should be https://asairhome.com/houses/<YOUR_HOUSE_ID>/climate.

Also, I uninstalled the nexia integration and it won't reinstall.

From the Log...

Unable to prepare setup for platform nexia.binary_sensor: Unable to set up component.
February 25, 2021, 12:36:05 PM – setup.py (ERROR) - message first occurred at February 25, 2021, 12:36:05 PM and shows up 3 times
Setup of nexia is taking longer than 300 seconds. Startup will proceed without waiting any longer
February 25, 2021, 12:36:05 PM – setup.py (ERROR)
Waiting on integrations to complete setup: nexia
February 25, 2021, 12:35:07 PM – bootstrap.py (WARNING) - message first occurred at February 25, 2021, 12:32:07 PM and shows up 4 times

ClimateDevice is deprecated, modify NexiaZone to extend ClimateEntity
February 25, 2021, 12:31:07 PM – Climate (WARNING)
BinarySensorDevice is deprecated, modify NexiaBinarySensor to extend BinarySensorEntity
February 25, 2021, 12:31:05 PM – Binary sensor (WARNING)

**Comment by RSI4Life-Hub** [comment]
Cool

**Comment by RSI4Life-Hub** [comment]
__

**Comment by bdraco** [comment]
Fixed in 0.9.7

Pass brand = BRAND_ASAIR from `nexia.const` to the constructor
